### ISSUE TITLE
Problem with OM variable in RUSLE_factors.js

### ISSUE THREAD

**Issue by jkrizan** [SoilWatch/soil-erosion-watch#11]
This line in RUSLE_factors.js has no sense: https://github.com/SoilWatch/soil-erosion-watch/blob/f25decaf65a8fcc41d8d505f40e99024e0affec6/RUSLE_factors.js#L129  
OM cannot be greater than or equal to 20 because of this line: https://github.com/SoilWatch/soil-erosion-watch/blob/f25decaf65a8fcc41d8d505f40e99024e0affec6/RUSLE_factors.js#L86  
So OM.gte(20) is never true.

**Comment by wouellette** [comment]
Hi @jkrizan,

Thanks for spotting it.

updated [here](https://github.com/SoilWatch/soil-erosion-watch/commit/52e97cee6325548216a9fe25bc1f6eeaeb7265b7).

Regards
