### ISSUE TITLE
download of layers

### ISSUE THREAD

**Issue by Ciaran1981** [SoilWatch/soil-erosion-watch#7]
A question rather than an issue. Is there a way to download the outputted layers?

**Comment by wouellette** [comment]
Hi Ciaran,

I added a functionality to export the viewport. Bear in mind it takes the viewport scale, which will most necessarily be of poorer resolution/quality than the nominal resolution you can see in the app. To download the raw geotiff, it is best you run the code on your GEE account and use the `export.image` GEE functions.

![image](https://user-images.githubusercontent.com/20474036/167928672-8f5e4182-4cd2-4034-8e99-90e879b71b98.png)

**Comment by Ciaran1981** [comment]
Great  thanks very much.
